language:
  python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev

addons:
  apt:
    packages:
      - texlive-latex-base

before_install:
  - export REQUIREMENTS_DEV_TXT=`python -c 'import sys;print("requirements" + str(sys.version_info.major) + "-dev.txt")'`
  - echo "REQUIREMENTS_DEV_TXT=$REQUIREMENTS_DEV_TXT"

install:
  - pip install -U pip
  - pip --version
  - pip install -r requirements.txt
  - pip install -r "$REQUIREMENTS_DEV_TXT"
  - python bin/downloads.py


before_script:
  - kpsewhich -version
  - which python

script:
  - TESTCOMMON_PASS_SKIPS=1 python runtest --verbose=2 -e test/system
